#!/usr/bin/env python3
import sys
import json
import csv
import re
from collections import defaultdict

CITY_NAMES = ['Tokyo', 'Aba', 'Abeokuta', 'Abia', 'Abidjan', 'Abobo',
              'Abu Dhabi', 'Abu Ghurayb', 'Acapulco', 'Accra', 'Ad Dammam',
              'Ad Diwaniyah', 'Adalia', 'Adana', 'Addis Abeba', 'Adelaide',
              'Aden', 'Adiyaman', 'Agadair', 'Agadir', 'Agra', 'Aguascalientes',
              'Ahmadabad', 'Ahvaz', 'Aidin', 'Ajmer', 'Akola', 'Al Basrah',
              'Al Basrah Al Qadimah', 'Al Jadida', 'Al Jazair', 'Al Kuwait',
              'Al Mawsil Al Jadidah', 'Al Qahirah', 'Al Sharjah', 'Al-sham',
              'Albuquerque', 'Aleksandrovsk', 'Alep', 'Aleppo', 'Alexandria',
              'Algiers', 'Aligarh', 'Allahabad', 'Almaty', 'Amagasaki',
              'Amaravati', 'Amman', 'Amravati', 'Amritsar', 'Amsterdam',
              'An Najaf', 'Ananindeua', 'Ankara', 'Ansan', 'Anshan', 'Antalya',
              'Antananarivo', 'Antipolo', 'Antwerp', 'Anyang', 'Anyang',
              'Aracaju', 'Arak', 'Arequipa', 'As Sulaymaniyah', 'As Suways',
              'Asansol', 'Asgabat', 'Ash Shariqah', 'Ashgabat', 'Asmara',
              'Astrakhan', 'Astrida', 'Asuncion', 'Athens', 'Aurangabad',
              'Austin', 'Azadshahr', 'Azilal', 'Bacolod', 'Bacolod City',
              'Baghdad', 'Bahawalpur', 'Baile Atha Cliath', 'Baku',
              'Balikpapan', 'Baltimore', 'Bamako', 'Bandar Lampung', 'Bandung',
              'Bangalore', 'Bangkok', 'Bangui', 'Banjarmasin', 'Baoding',
              'Baoji', 'Baotou Shi', 'Barcelona', 'Bareli', 'Barnaul',
              'Barquisimeto', 'Barranquilla', 'Beijing Shi', 'Beira', 'Beirut',
              'Bejraburi', 'Bekasi', 'Belem', 'Belfast', 'Belford Roxo',
              'Belgaum', 'Belgrade', 'Belo Horizonte', 'Bengbu', 'Benghazi',
              'Benin', 'Benoni', 'Benxi', 'Berlin', 'Bhatpara', 'Bhavnagar',
              'Bhilai', 'Bhiwandi', 'Bhopal', 'Bhubaneswar', 'Bikaner',
              'Birmingham', 'Bishkek', 'Blantyre', 'Bloemfontein', 'Boayan',
              'Bogor', 'Bogota', 'Boksburg', 'Bombay', 'Bor Sa`id',
              'Bosna-sarai', 'Bouake', 'Brampton', 'Brasilia', 'Brazzaville',
              'Bremen', 'Brisbane', 'Bristol', 'Bronx', 'Brooklyn', 'Brusa',
              'Brussels', 'Bucaramanga', 'Bucuresti', 'Budapest',
              'Buenos Aires', 'Bulawayo', 'Burleigh School', 'Bursa', 'Busan',
              'Caesarea', 'Cagayan De Oro', 'Calabar', 'Calcutta', 'Calgary',
              'Cali', 'Calicut', 'Callao', 'Camayenne', 'Campinas',
              'Campo Grande', 'Cancun', 'Cangzhou', 'Cape Town', 'Caracas',
              'Carrefour', 'Cartagena', 'Casablanca', 'Ceara', 'Cebu',
              'Central', 'Chandaburi', 'Chandigarh', 'Changchun', 'Changde',
              'Changsha', 'Changwat Chachoengsao', 'Changwat Chaiyaphum',
              'Changwat Chiang Mai', 'Changwat Chiang Rai',
              'Changwat Chon Buri', 'Changwat Chumphon', 'Changwat Kalasin',
              'Changwat Krabi', 'Changwat Lampang', 'Changwat Loei',
              'Changwat Maha Sarakham', 'Changwat Nakhon Phanom',
              'Changwat Nakhon Rat Sima', 'Changwat Nakhon Sawan',
              'Changwat Nakhon Si Thammarat', 'Changwat Nan',
              'Changwat Nong Khai', 'Changwat Nonthaburi',
              'Changwat Phatthalung', 'Changwat Phetchabun', 'Changwat Phichit',
              'Changwat Phitsanulok', 'Changwat Phra Nakhon Si Ayutthaya',
              'Changwat Prachuap Khiri Khan', 'Changwat Rat Buri',
              'Changwat Roi Et', 'Changwat Sakon Nakhon',
              'Changwat Samut Prakan', 'Changwat Sawankhalok',
              'Changwat Songkhla', 'Changwat Sukhothai', 'Changwat Suphan Buri',
              'Changwat Surat Thani', 'Changwat Surin', 'Changwat Tak',
              'Changwat Trang', 'Changwat Uttaradit', 'Changwat Yala',
              'Changwat Yasothon', 'Changzhou', 'Charlotte', 'Cheboksary',
              'Chelyabinsk', 'Cheng', 'Chengde', 'Chengdu', 'Chiba', 'Chicago',
              'Chiclayo', 'Chihuahua', 'Chimahi', 'Chimalhuacan', 'Chisinau',
              'Chittagong', 'Chitungwiza', 'Chkalov', 'Chongqing', 'Chonju',
              'Cibitoke', 'Ciudad De Montevideo', 'Ciudad Guayana',
              'Ciudad Juarez', 'Cleveland', 'Cluj', 'Cochabamba', 'Coimbatore',
              'Cologne', 'Colombo', 'Columbus', 'Constantine', 'Constantinople',
              'Contagem', 'Copenhagen', 'Cordoba', 'Cotonou',
              'Cuautitlan Izcalli', 'Cucuta', 'Cuiaba', 'Culiacan', 'Curitiba',
              'Cuttack', 'Da Huryee', 'Da Nang', 'Dadiangas', 'Daejeon',
              'Dagon', 'Dagu', 'Dakar', 'Dalian', 'Dallas', 'Damascus',
              'Dandong', 'Dang', 'Dar Es Salaam', 'Dasmarinas', 'Dasmarinas',
              'Datong', 'Davao', 'Davao City', 'Dehra Dun', 'Delhi', 'Denver',
              'Depok', 'Detroit', 'Dhaka', 'Dhanukha', 'Diyarbakir',
              'Djuschambe', 'Dongliao', 'Dortmund', 'Douala', 'Dresden',
              'Dubai', 'Dubayy', 'Dublin', 'Duisburg', 'Duque De Caxias',
              'Durango', 'Durban', 'Durgapur', 'Dusseldorf', 'Ecatepec',
              'Edessa', 'Edinburgh', 'Edmonton', 'Edo', 'Eiko',
              'El Mahalla El Kubra', 'El Paso', 'El-hodeidah', 'Elazig',
              'Enugu', 'Erzerum', 'Esfahan', 'Eskisehir', 'Essaouira', 'Essen',
              'Eva Peron', 'Faisalabad', 'Faridabad', 'Feira De Santana',
              'Felicitas Julia', 'Fez', 'Fort Fureau', 'Fort Worth', 'Foshan',
              'Frankfurt Am Main', 'Freetown', 'Fresno', 'Fukuoka', 'Funabashi',
              'Fushun', 'Fuxin', 'Fuzhou', 'Gabouk', 'Gampheang Phet', 'Garoua',
              'Gaziantep', 'Gdansk', 'General Santos City', 'Geneve', 'Genova',
              'Ghaziabad', 'Ghom', 'Gizeh', 'Glasgow', 'Goiania', 'Gold Coast',
              'Gomel', 'Gorakhpur', 'Goteborg', 'Grand Dakar', 'Guadalajara',
              'Guadalupe', 'Guangzhou', 'Guarulhos', 'Guatemala', 'Guayaquil',
              'Guilin', 'Guiyang', 'Gujranwala', 'Gulbarga', 'Guntur',
              'Guwahati', 'Gwalior', 'Ha Noi', 'Hachioji', 'Hai Phong',
              'Haikou', 'Hamadan', 'Hamah', 'Hamamatsu', 'Hamburg', 'Hamhung',
              'Hamilton', 'Hamitabat', 'Handan', 'Hangzhou', 'Hanover', 'Haora',
              'Harare', 'Harbin', 'Hargeisa', 'Havana', 'Hefei', 'Hegang',
              'Helsinki', 'Hengshui', 'Hengyang', 'Hermosillo', 'Himeji',
              'Hims', 'Hiroshima', 'Ho Chi Minh City', 'Hohhot', 'Hong Kong',
              'Houston', 'Huaibei', 'Huainan', 'Huaiyin', 'Hubli', 'Hyderabad',
              'Hyderabad', 'Ibadan', 'Ichikawa', 'Ilorin', 'Indianapolis',
              'Indore', 'Ipoh', 'Iquitos', 'Irbil', 'Irkutsk', 'Islamabad',
              'Istanbul', 'Izhevsk', 'Izmir', 'Jabalpur', 'Jaboatao',
              'Jacksonville', 'Jaipur', 'Jaizan', 'Jakarta', 'Jalandhar',
              'Jammu', 'Jamnagar', 'Jamshedpur', 'Jerusalem', 'Jhapa',
              'Jiamusi', 'Jiangmen', 'Jiaojiang', 'Jiaozuo', 'Jiaxing',
              'Jibuti', 'Jiddah', 'Jilin', 'Jinan', 'Jining', 'Joao Pessoa',
              'Jodhpur', 'Johannesburg', 'Johor Bahru', 'Joinville', 'Jos',
              'Juarez', 'Juiz De Fora', 'Kabul', 'Kaduna', 'Kagoshima',
              'Kahriz', 'Kaifeng', 'Kailali', 'Kaisaria', 'Kalat',
              'Kaliningrad', 'Kalyan', 'Kampala', 'Kananga', 'Kanazawa', 'Kano',
              'Kanpur', 'Kansas City', 'Kaohsiung', 'Kaohsiung', 'Karachi',
              'Karaj', 'Kathmandu', 'Katsina', 'Kawaguchi', 'Kawasaki',
              'Kawasaki', 'Kayseri', 'Kazan', 'Kemerovo', 'Kerman',
              'Kermanshah', 'Khabarovsk', 'Kharkiv', 'Khartoum', 'Khemisset',
              'Khenifra', 'Khouribga', 'Khulna', 'Kiev', 'Kigale', 'Kigali',
              'Kingston', 'Kinshasa', 'Kirkuk', 'Kirov', 'Kisangani',
              'Kitakyushu', 'Klang', 'Kobe', 'Kocaeli', 'Kochi', 'Koeln',
              'Kolhapur', 'Konia', 'Konya', 'Kosovo', 'Kota', 'Kota Kinabalu',
              'Kousseri', 'Kowloon', 'Krakow', 'Krasnodar', 'Krasnoyarsk',
              'Kryvyy Rih', 'Kuala Lumpur', 'Kuching', 'Kumamoto', 'Kumasi',
              'Kunming', 'Kurashiki', 'Kwangju', 'Kyoto', 'La Paz', 'La Plata',
              'Lagos', 'Lahore', 'Lakhnau', 'Langfang', 'Lanzhou', 'Larache',
              'Las Pinas', 'Las Vegas', 'Leeds', 'Leipzig', 'Leon', 'Leui',
              'Liaoyang', 'Libreville', 'Lilongwe', 'Lima', 'Lipetsk', 'Lisboa',
              'Liuzhou', 'Liverpool', 'Lobh Buri', 'Lodz', 'Lome', 'London',
              'Londrina', 'Long Beach', 'Lopez Mateos', 'Los Angeles',
              'Luancheng', 'Luanda', 'Lubumbashi', 'Ludhiana', 'Luoyang',
              'Lusaka', 'Lvov', 'Lyon', 'Maanshan', 'Maceio', 'Madras',
              'Madrid', 'Madurai', 'Maha Sarakam', 'Maiduguri', 'Maisuru',
              'Makasar', 'Makhachkala', 'Malaga', 'Malang', 'Malatia',
              'Malatya', 'Malegaon', 'Manado', 'Managua', 'Manaus', 'Mandalay',
              'Manila', 'Mansilingan', 'Maoming', 'Maputo', 'Mar Del Plata',
              'Maracaibo', 'Marrakesh', 'Marseille', 'Mashhad', 'Matamoros',
              'Matola', 'Matsudo', 'Matsuyama', 'Mawlamyine', 'Mbuji-mayi',
              'Mecca', 'Medan', 'Medellin', 'Medina', 'Meerut', 'Meknes',
              'Melbourne', 'Memphis', 'Mendoza', 'Merida', 'Mersin', 'Mesa',
              'Mexicali', 'Mexico', 'Milan', 'Milwaukee', 'Minsk',
              'Mississauga', 'Mixco', 'Mogadishu', 'Mombasa', 'Monrovia',
              'Monterrey', 'Montevideo', 'Montreal', 'Moradabad', 'Morelia',
              'Moscow', 'Mosul', 'Mudanjiang', 'Multan', 'Munich', 'Mwanza',
              'Naberezhnyye Chelny', 'Nagara Pathom', 'Nagoya', 'Nagpur',
              'Nairobi', 'Namangan', 'Nanchang', 'Nanded', 'Nangi', 'Nanjing',
              'Nanning', 'Nantong', 'Naples', 'Napoli', 'Naradhivas',
              'Nashville', 'Nasik', 'Natal', 'Naucalpan', 'Neijiang', 'Nerima',
              'New Orleans', 'New Patna', 'New South Memphis', 'New York',
              'Newcastle', 'Nezahualcoyotl', 'Niamey', 'Niigata', 'Nikolaev',
              'Ningbo', 'Nishinomiya', 'Niteroi', 'Nizhniy Novgorod',
              'North Kansas City', 'Nouakchott', 'Nova Iguacu', 'Novokuznetsk',
              'Novosibirsk', 'Nuremberg', 'Odesa', 'Ogun', 'Oita', 'Okayama',
              'Okene', 'Oklahoma City', 'Omdurman', 'Omsk', 'Onicha', 'Onitsha',
              'Orenburg', 'Orumiyeh', 'Osaka', 'Osasco', 'Oshogbo', 'Oslo',
              'Ottawa', 'Ouagadouga', 'Ouagadougou', 'Ouarzazate', 'Oyo',
              'Padang', 'Padumdhani', 'Palembang', 'Palermo', 'Panchiao',
              'Panshan', 'Panzhihua', 'Paris', 'Patna', 'Peking', 'Penza',
              'Pereira', 'Perm', 'Perth', 'Peshawar', 'Pest', 'Petaling Jaya',
              'Philadelphia', 'Phnom Penh', 'Phoenix', 'Pietermaritzburg',
              'Pimpri', 'Pingdingshan', 'Pointe-noire', 'Pontianak',
              'Port Elizabeth', 'Port Harcourt', 'Port-au-prince', 'Portland',
              'Porto Alegre', 'Poti', 'Poznan', 'Praha', 'Pretoria', 'Puebla',
              'Pune', 'Puyang', 'Pyongyang', 'Qingdao', 'Qinhuangdao',
              'Qiqihar', 'Qom', 'Quebec', 'Queretaro', 'Quetta', 'Quezon',
              'Quilmes', 'Quito', 'Rabat', 'Raipur', 'Rajkot', 'Rajpur',
              'Rajshahi', 'Ranchi', 'Rasht', 'Rawalpindi', 'Recife', 'Reunion',
              'Reynosa', 'Ribeirao Preto', 'Riga', 'Rio De Janeiro', 'Riyadh',
              'Rome', 'Rongcheng', 'Rosario', 'Rostov-na-donu', 'Rotterdam',
              'Rupandehi', 'Ryazan', 'Sacramento', 'Safi', 'Sagamihara',
              'Saharanpur', 'Saint Petersburg', 'Sakai', 'Sale', 'Salta',
              'Saltillo', 'Salvador', 'Samara', 'San Antonio', 'San Diego',
              'San Francisco', 'San Jose', 'San Juan', 'San Luis Potosi',
              'San Miguel De Tucuman', 'San Nicolas De Los Garza',
              'San Pedro Sula', 'San Salvador', 'Sanaa',
              'Santa Cruz De La Sierra', 'Santa Fe', 'Santa Marta', 'Santiago',
              'Santiago', 'Santiago De Cuba', 'Santo Andre', 'Santo Domingo',
              'Sao Bernardo Do Campo', 'Sao Goncalo', 'Sao Joao De Meriti',
              'Sao Jose Dos Campos', 'Sao Luis', 'São Paulo', 'Sapporo',
              'Sar-e Pol', 'Saratov', 'Sargodha', 'Seattle', 'Selam',
              'Semarang', 'Sendai', 'Seoul', 'Settat', 'Sevilla', 'Shah Alam',
              'Shanghai', 'Shantou', 'Shaoguan', 'Sharjah', 'Shashi',
              'Sheffield', 'Shenyang', 'Shenzhen', 'Shihezi', 'Shiliguri',
              'Shiraz', 'Shizuoka', 'Sholapur', 'Sialkot', 'Singapore',
              'Skopje', 'Sofia', 'Sokoto', 'Songnam', 'Sorocaba',
              'South Boston', 'Soweto', 'Spetsgorodok', 'Srinagar', 'Stockholm',
              'Stuttgart', 'Suigen', 'Sultanah', 'Surabaya', 'Surakarta',
              'Surat', 'Suwon', 'Suzhou', 'Sydney', 'Tabriz', 'Taegu', 'Taejon',
              'Taguig', 'Taian', 'Taichung', 'Tainan', 'Taipei', 'Taiyuan',
              'Taizhou', 'Tandjile', 'Tanger', 'Tangerang', 'Tanggu', 'Tangier',
              'Tangshan', 'Taounate', 'Taroudannt', 'Tashkent', 'Taza',
              'Tbilisi', 'Tegucigalpa', 'Tehran', 'Tembisa', 'Teresina',
              'Thana', 'The Hague', 'Thiruvananthapuram', 'Tianjin', 'Tijuana',
              'Tipaza', 'Tiruchchirappalli', 'Tirunelveli', 'Tlalnepantla',
              'Tlaquepaque', 'Toluca', 'Tolyatti', 'Tomsk', 'Torino', 'Toronto',
              'Torreon', 'Tripoli', 'Trujillo', 'Tucson', 'Tucuman', 'Tula',
              'Tunes', 'Turin', 'Tuxtla Gutierrez', 'Tyumen', 'Uberlandia',
              'Ufa', 'Uijongbu', 'Ujjain', 'Ulhasnagar', 'Ulyanovsk',
              'Umm Durman', 'Unguja Ukuu', 'Urfa', 'Urumqi', 'Ussuriyskiy',
              'Utsunomiya', 'Vadodara', 'Valencia', 'Valencia', 'Vancouver',
              'Varanasi', 'Vaucluse', 'Veracruz', 'Vereeniging', 'Vijayawada',
              'Vilnius', 'Virginia Beach', 'Visakhapatnam', 'Vladivostok',
              'Volgograd', 'Voronezh', 'Wahran', 'Wahren', 'Warab', 'Warangal',
              'Warri', 'Warsaw', 'Washington', 'Welkom', 'Wenzhou', 'Wien',
              'Winnipeg', 'Wroclaw', 'Wuhan', 'Wuhu', 'Wuxi', 'Xiamen', 'Xian',
              'Xiangfan', 'Xianyang', 'Xingtai', 'Xining', 'Xinxiang',
              'Xinyang', 'Xuchang', 'Xuzhou', 'Yancheng', 'Yangzhou', 'Yantai',
              'Yaounde', 'Yaroslavl', 'Yazd', 'Yekaterinburg', 'Yerevan',
              'Yichang', 'Yinchuan', 'Yingkou', 'Yogyakarta', 'Yokohama',
              'Yokosuka', 'Yongkang', 'Yono', 'Yueyang', 'Yunfu', 'Zagreb',
              'Zahedan', 'Zamboanga', 'Zamboanga City', 'Zapopan', 'Zaragoza',
              'Zaria', 'Zhangjiakou', 'Zhangzhou', 'Zhanjiang', 'Zhengzhou',
              'Zhenjiang', 'Zhuhai', 'Zhuzhou', 'Zibo', 'Zigong', 'Zunyi']

CAPITALS = [('AFGHANISTAN', 'KABUL'), ('ALBANIA', 'TIRANA'),
            ('ALGERIA', 'ALGIERS'), ('ANDORRA', 'ANDORRA LA VELLA'),
            ('ANGOLA', 'LUANDA'), ('Antigua and Barbuda', "St. JOHN'S"),
            ('ARGENTINA', 'BUENOS AIRES'), ('ARMENIA', 'YEREVAN'),
            ('AUSTRALIA', 'CANBERRA'), ('AUSTRIA', 'VIENNA'),
            ('AZERBAIJAN', 'BAKU'), ('The Bahamas', 'NASSAU'),
            ('BAHRAIN', 'MANAMA'), ('BANGLADESH', 'DHAKA'),
            ('BARBADOS', 'BRIDGETOWN'), ('BELARUS', 'MINSK'),
            ('BELGIUM', 'BRUSSELS'), ('BELIZE', 'BELMOPAN'),
            ('BENIN', 'PORTO-NOVO'), ('BHUTAN', 'THIMPHU'),
            ('BOLIVIA', 'SUCRE'), ('Bosnia and Herzegovina', 'SARAJEVO'),
            ('BOTSWANA', 'GABORONE'), ('BRAZIL', 'BRASILIA'),
            ('BRUNEI', 'BANDAR SERI BEGAWAN'), ('BULGARIA', 'SOFIA'),
            ('BURKINA FASO', 'OUAGADOUGOU'), ('BURUNDI', 'BUJUMBURA'),
            ('Cape Verde', 'PRAIA'), ('CAMBODIA', 'PHNOM PENH'),
            ('CAMEROON', 'YAOUNDE'), ('CANADA', 'OTTAWA'),
            ('CENTRAL AFRICAN REPUBLIC', 'BANGUI'), ('CHAD', "N'DJAMENA"),
            ('CHILE', 'SANTIAGO'), ('CHINA', 'BEIJING'),
            ('COLOMBIA', 'BOGOTÁ'), ('COMOROS', 'MORONI'),
            ('Democratic Republic of the Congo', 'KINSHASA'), ('CYPRUS', 'NICOSIA'),
            ('COSTA RICA', 'San José'), ("CÔTE D'IVOIRE", 'YAMOUSSOUKRO'),
            ('CROATIA', 'ZAGREB'), ('CUBA', 'HAVANA'),
            ('Czechia', 'PRAGUE'), ('DENMARK', 'COPENHAGEN'),
            ('DJIBOUTI', 'DJIBOUTI'), ('DOMINICA', 'ROSEAU'),
            ('DOMINICAN REPUBLIC', 'SANTO DOMINGO'), ('ECUADOR', 'QUITO'),
            ('EGYPT', 'CAIRO'), ('EL SALVADOR', 'SAN SALVADOR'),
            ('EQUATORIAL GUINEA', 'MALABO'), ('ERITREA', 'ASMARA'),
            ('ESTONIA', 'TALLINN'), ('ETHIOPIA', 'ADDIS ABABA'),
            ('FEDERATED STATES OF MICRONESIA', 'PALIKIR'), ('FIJI', 'SUVA'),
            ('FINLAND', 'HELSINKI'), ('FRANCE', 'PARIS'),
            ('GABON', 'LIBREVILLE'), ('Gambia', 'BANJUL'),
            ('GEORGIA', 'TBILISI'), ('GERMANY', 'BERLIN'),
            ('GREECE', 'ATHENS'), ('GRENADA', "St. GEORGE'S"),
            ('GUATEMALA', 'GUATEMALA CITY'), ('GUINEA', 'CONAKRY'),
            ('GUINEA-BISSAU', 'BISSAU'), ('GUYANA', 'GEORGETOWN'),
            ('HAITI', 'PORT-AU-PRINCE'), ('HONDURAS', 'TEGUCIGALPA'),
            ('HUNGARY', 'BUDAPEST'), ('ICELAND', 'Reykjavík'),
            ('INDIA', 'NEW DELHI'), ('INDONESIA', 'JAKARTA'),
            ('IRAN', 'TEHRAN'), ('IRAQ', 'BAGHDAD'),
            ('IRELAND', 'DUBLIN'), ('GHANA', 'ACCRA'),
            ('ISRAEL', 'JERUSALEM'), ('ISRAEL', 'TEL AVIV'),
            ('JAMAICA', 'KINGSTON'), ('JAPAN', 'TOKYO'),
            ('JORDAN', 'AMMAN'), ('ITALY', 'ROME'),
            ('KAZAKHSTAN', 'ASTANA'), ('KENYA', 'NAIROBI'),
            ('KIRIBATI', 'SOUTH TARAWA'), ('KOSOVO', 'PRISTINA'),
            ('KUWAIT', 'KUWAIT CITY'), ('KYRGYZSTAN', 'BISHKEK'),
            ('LAOS', 'VIENTIANE'), ('LATVIA', 'RIGA'),
            ('LESOTHO', 'MASERU'), ('LIBERIA', 'MONROVIA'),
            ('LIBYA', 'TRIPOLI'), ('LIECHTENSTEIN', 'VADUZ'),
            ('LITHUANIA', 'VILNIUS'), ('LUXEMBOURG', 'LUXEMBOURG'),
            ('Macedonia', 'SKOPJE'), ('LEBANON', 'BEIRUT'),
            ('MADAGASCAR', 'ANTANANARIVO'), ('MALAWI', 'LILONGWE'),
            ('MALAYSIA', 'KUALA LUMPUR'), ('MALDIVES', 'Malé'),
            ('MALI', 'BAMAKO'), ('MALTA', 'VALLETTA'),
            ('MARSHALL ISLANDS', 'MAJURO'), ('MAURITANIA', 'NOUAKCHOTT'),
            ('MAURITIUS', 'PORT LOUIS'), ('MEXICO', 'MEXICO CITY'),
            ('MOLDOVA', 'Chișinău'), ('MONACO', 'MONACO'),
            ('MONGOLIA', 'ULAANBAATAR'), ('MONTENEGRO', 'PODGORICA'),
            ('MOROCCO', 'RABAT'), ('MOZAMBIQUE', 'MAPUTO'),
            ('MYANMAR', 'Naypyidaw'), ('NAMIBIA', 'WINDHOEK'),
            ('NAURU', 'YAREN'), ('NEPAL', 'KATHMANDU'),
            ('THE NETHERLANDS', 'AMSTERDAM'), ('NEW ZEALAND', 'WELLINGTON'),
            ('NICARAGUA', 'MANAGUA'), ('NIGER', 'NIAMEY'),
            ('NORTH KOREA', 'PYONGYANG'), ('NORWAY', 'OSLO'),
            ('OMAN', 'MUSCAT'), ('PAKISTAN', 'ISLAMABAD'),
            ('PALAU', 'NGERULMUD'), ('Palestinian Territories', 'RAMALLAH'),
            ('PANAMA', 'PANAMA CITY'), ('PAPUA NEW GUINEA', 'PORT MORESBY'),
            ('PARAGUAY', 'ASUNCIÓN'), ('PERU', 'LIMA'),
            ('PHILIPPINES', 'MANILA'), ('POLAND', 'WARSAW'),
            ('PORTUGAL', 'LISBON'), ('QATAR', 'DOHA'),
            ('Congo-Brazzaville', 'BRAZZAVILLE'), ('ROMANIA', 'BUCHAREST'),
            ('RUSSIA', 'MOSCOW'), ('RWANDA', 'KIGALI'),
            ('Saint Kitts and Nevis', 'BASSETERRE'), ('NIGERIA', 'ABUJA'),
            ('SAINT VINCENT AND THE GRENADINES', 'KINGSTOWN'), ('SAINT LUCIA', 'CASTRIES'),
            ('SAMOA', 'APIA'), ('SAN MARINO', 'SAN MARINO'),
            ('São Tomé and Príncipe', 'SÃO TOMÉ'), ('SAUDI ARABIA', 'RIYADH'),
            ('SENEGAL', 'DAKAR'), ('SERBIA', 'BELGRADE'),
            ('SEYCHELLES', 'VICTORIA'), ('SIERRA LEONE', 'FREETOWN'),
            ('SINGAPORE', 'SINGAPORE'), ('SLOVAKIA', 'BRATISLAVA'),
            ('SLOVENIA', 'LJUBLJANA'), ('SOLOMON ISLANDS', 'HONIARA'),
            ('SOMALIA', 'MOGADISHU'), ('SOUTH AFRICA', 'BLOEMFONTEIN'),
            ('SOUTH AFRICA', 'CAPE TOWN'), ('SOUTH AFRICA', 'PRETORIA'),
            ('SOUTH KOREA', 'SEOUL'), ('SOUTH SUDAN', 'JUBA'),
            ('SPAIN', 'MADRID'), ('SRI LANKA', 'COLOMBO'),
            ('SRI LANKA', 'SRI JAYAWARDENEPURA KOTTE'), ('SUDAN', 'KHARTOUM'),
            ('SURINAME', 'PARAMARIBO'), ('Eswatini', 'MBABANE'),
            ('SWEDEN', 'STOCKHOLM'), ('SWITZERLAND', 'BERN'),
            ('SYRIA', 'DAMASCUS'), ('TAJIKISTAN', 'DUSHANBE'),
            ('TANZANIA', 'DODOMA'), ('THAILAND', 'BANGKOK'),
            ('East Timor', 'DILI'), ('TOGO', 'LOMÉ'),
            ('TRINIDAD AND TOBAGO', 'PORT OF SPAIN'), ('TUNISIA', 'TUNIS'),
            ('TURKEY', 'ANKARA'), ('TURKMENISTAN', 'ASHGABAT'),
            ('TUVALU', 'Vaiaku'), ('UGANDA', 'KAMPALA'),
            ('UKRAINE', 'KIEV'), ('TONGA', "Nuku'alofa"),
            ('UNITED ARAB EMIRATES', 'ABU DHABI'), ('UNITED KINGDOM', 'LONDON'),
            ('URUGUAY', 'MONTEVIDEO'), ('UZBEKISTAN', 'TASHKENT'),
            ('VANUATU', 'PORT VILA'), ('VATICAN CITY', 'VATICAN CITY'),
            ('VENEZUELA', 'CARACAS'), ('VIETNAM', 'HANOI'),
            ('YEMEN', "SANA'A"), ('United States of America', 'WASHINGTON, D.C.'),
            ('ZAMBIA', 'LUSAKA'), ('ZIMBABWE', 'HARARE')]


def read_csv_into_dict(f):
    r = csv.reader(f, delimiter=';')
    header = next(r)
    result = {}
    for row in r:
        item = {}
        for i in range(1, len(row)):
            item[header[i]] = row[i]
        result[row[0]] = item
    return result

if len(sys.argv) < 2:
    print('Usage: {} <path_to_places_json_or_csv>'.format(sys.argv[0]))
    sys.exit(1)

with open(sys.argv[1], 'r') as f:
    if '.csv' in sys.argv[1]:
        places = read_csv_into_dict(f)
    else:
        places = json.load(f)

countries_name = re.sub(r'places(?=[._-])', 'countries', sys.argv[1])
with open(countries_name, 'r') as f:
    if '.csv' in countries_name:
        countries = read_csv_into_dict(f)
    else:
        countries = json.load(f)

place_names = defaultdict(list)
for pid, names in places.items():
    for k in ('name_en', 'int_name', 'name'):
        if k in names:
            place_names[names[k].lower()].append(pid)

for city in CITY_NAMES:
    if city.lower() not in place_names:
        print('City not found: {}'.format(city))

for country, city in CAPITALS:
    pids = place_names.get(city.lower())
    if not pids:
        print('Capital not found: {}, {}'.format(city.title(), country.title()))
    else:
        pcountries = set()
        for pid in pids:
            for k, name in countries.get(str(places[pid]['country']), {}).items():
                if k in ('name_en', 'int_name', 'name'):
                    pcountries.add(name.lower())
        if country.lower() not in pcountries:
            print('Country {} for capital {} not found, instead: {}'.format(
                country.title(), city.title(), ', '.join([c.title() for c in sorted(pcountries)])))
