#!/usr/bin/env python3
import sys
import json
import csv
import re
from collections import defaultdict

CITY_NAMES = ['Tokyo', 'Aba', 'Abeokuta', 'Abia', 'Abidjan', 'Abobo',
              'Abu Dhabi', 'Abu Ghraib', 'Acapulco', 'Accra', 'Dammam',
              'Ad Diwaniyah', 'Adalia', 'Adana', 'Addis Ababa', 'Adelaide',
              'Aden', 'Adiyaman', 'Agadir', 'Agra', 'Aguascalientes',
              'Ahmadabad', 'Ahvaz', 'Aydin', 'Ajmer', 'Akola', 'Basra',
              'Al Basrah Al Qadimah', 'El Jadida', 'Kuwait City',
              'Mosul', 'Al Qahirah', 'Sharjah',
              'Albuquerque', 'Aleksandrovsk', 'Aleppo', 'Alexandria',
              'Algiers', 'Aligarh', 'Allahabad', 'Almaty', 'Amagasaki',
              'Amaravati', 'Amman', 'Amravati', 'Amritsar', 'Amsterdam',
              'Najaf', 'Ananindeua', 'Ankara', 'Ansan', 'Anshan', 'Antalya',
              'Antananarivo', 'Antipolo', 'Antwerp', 'Anyang', 'Anyang',
              'Aracaju', 'Arak', 'Arequipa', 'As Sulaymaniyah', 'Suez',
              'Asansol', 'Ashgabat', 'Ash Shariqah', 'Ashgabat', 'Asmara',
              'Astrakhan', 'Astrida', 'Asuncion', 'Athens', 'Aurangabad',
              'Austin', 'Azadshahr', 'Azilal', 'Bacolod', 'Bacolod City',
              'Baghdad', 'Bahawalpur', 'Baku',
              'Balikpapan', 'Baltimore', 'Bamako', 'Bandar Lampung', 'Bandung',
              'Bengaluru', 'Bangkok', 'Bangui', 'Banjarmasin', 'Baoding',
              'Baoji', 'Baotou', 'Barcelona', 'Bareli', 'Barnaul',
              'Barquisimeto', 'Barranquilla', 'Beijing', 'Beira', 'Beirut',
              'Phetchaburi', 'Bekasi', 'Belem', 'Belfast', 'Belford Roxo',
              'Belgaum', 'Belgrade', 'Belo Horizonte', 'Bengbu', 'Benghazi',
              'Benin City', 'Benoni', 'Benxi', 'Berlin', 'Bhatpara', 'Bhavnagar',
              'Bhilai', 'Bhiwandi', 'Bhopal', 'Bhubaneswar', 'Bikaner',
              'Birmingham', 'Bishkek', 'Blantyre', 'Bloemfontein',
              'Bogor', 'Bogota', 'Boksburg', 'Bombay', 'Port Said',
              'Sarajevo', 'Bouake', 'Brampton', 'Brasilia', 'Brazzaville',
              'Bremen', 'Brisbane', 'Bristol', 'Brooklyn', 'Bursa',
              'Brussels', 'Bucaramanga', 'Bucharest', 'Budapest',
              'Buenos Aires', 'Bulawayo', 'Bursa', 'Busan',
              'Caesarea', 'Cagayan De Oro', 'Calabar', 'Calcutta', 'Calgary',
              'Cali', 'Kozhikode', 'Callao', 'Campinas',
              'Campo Grande', 'Cancun', 'Cangzhou', 'Cape Town', 'Caracas',
              'Carrefour', 'Cartagena', 'Casablanca', 'Cebu City',
              'Central', 'Chanthaburi', 'Chandigarh', 'Changchun', 'Changde',
              'Changsha', 'Changzhou', 'Charlotte', 'Cheboksary',
              'Chelyabinsk', 'Cheng', 'Chengde', 'Chengdu', 'Chiba', 'Chicago',
              'Chiclayo', 'Chihuahua', 'Cimahi', 'Chimalhuacan', 'Chișinău',
              'Chittagong', 'Chitungwiza', 'Chkalov', 'Chongqing', 'Jeonju',
              'Cibitoke', 'Ciudad Guayana',
              'Ciudad Juarez', 'Cleveland', 'Cluj-Napoca', 'Cochabamba', 'Coimbatore',
              'Cologne', 'Colombo', 'Columbus', 'Constantine',
              'Contagem', 'Copenhagen', 'Cordoba', 'Cotonou',
              'Cuautitlan Izcalli', 'Cucuta', 'Cuiaba', 'Culiacan', 'Curitiba',
              'Cuttack', 'Danang', 'Daejeon',
              'Dagon', 'Dagu', 'Dakar', 'Dalian', 'Dallas', 'Damascus',
              'Dandong', 'Dang', 'Dar Es Salaam', 'Dasmarinas', 'Dasmarinas',
              'Datong', 'Davao', 'Davao City', 'Dehradun', 'Delhi', 'Denver',
              'Depok', 'Detroit', 'Dhaka', 'Diyarbakir',
              'Dushanbe', 'Dongliao', 'Dortmund', 'Douala', 'Dresden',
              'Dubai', 'Dublin', 'Duisburg', 'Duque De Caxias',
              'Durango', 'Durban', 'Durgapur', 'Dusseldorf', 'Ecatepec de Morelos',
              'Edessa', 'Edinburgh', 'Edmonton', 'Edo', 'Elko',
              'El Mahalla El Kubra', 'El Paso', 'Al Hudaydah', 'Elazig',
              'Enugu', 'Erzurum', 'Isfahan', 'Eskisehir', 'Essaouira', 'Essen',
              'Faisalabad', 'Faridabad', 'Feira De Santana',
              'Fez', 'Kousseri', 'Fort Worth', 'Foshan',
              'Frankfurt Am Main', 'Freetown', 'Fresno', 'Fukuoka', 'Funabashi',
              'Fushun', 'Fuxin', 'Fuzhou', 'Tabuk', 'Kamphaeng Phet', 'Garoua',
              'Gaziantep', 'Gdansk', 'General Santos', 'Geneve', 'Genova',
              'Ghaziabad', 'Qom', 'Giza', 'Glasgow', 'Goiania', 'Gold Coast',
              'Homel', 'Gorakhpur', 'Gothenburg', 'Guadalajara',
              'Guadalupe', 'Guangzhou', 'Guarulhos', 'Guatemala', 'Guayaquil',
              'Guilin', 'Guiyang', 'Gujranwala', 'Kalaburagi', 'Guntur',
              'Guwahati', 'Gwalior', 'Hanoi', 'Hachioji', 'Haiphong',
              'Haikou', 'Hamadan', 'Hamah', 'Hamamatsu', 'Hamburg', 'Hamhung',
              'Hamilton', 'Hamitabat', 'Handan', 'Hangzhou', 'Hanover', 'Howrah',
              'Harare', 'Harbin', 'Hargeisa', 'Havana', 'Hefei', 'Hegang',
              'Helsinki', 'Hengshui', 'Hengyang', 'Hermosillo', 'Himeji',
              'Homs', 'Hiroshima', 'Ho Chi Minh City', 'Hohhot', 'Hong Kong',
              'Houston', 'Huaibei', 'Huainan', 'Huai\'an', 'Hubballi', 'Hyderabad',
              'Hyderabad', 'Ibadan', 'Ichikawa', 'Ilorin', 'Indianapolis',
              'Indore', 'Ipoh', 'Iquitos', 'Erbil', 'Irkutsk', 'Islamabad',
              'Istanbul', 'Izhevsk', 'Izmir', 'Jabalpur', 'Jaboatao dos Guararapes',
              'Jacksonville', 'Jaipur', 'Jizan', 'Jakarta', 'Jalandhar',
              'Jammu', 'Jamnagar', 'Jamshedpur', 'Jerusalem',
              'Jiamusi', 'Jiangmen', 'Jiaojiang', 'Jiaozuo', 'Jiaxing',
              'Djibouti', 'Jeddah', 'Jilin', 'Jinan', 'Jining', 'Joao Pessoa',
              'Jodhpur', 'Johannesburg', 'Johor Bahru', 'Joinville', 'Jos',
              'Juarez', 'Juiz De Fora', 'Kabul', 'Kaduna', 'Kagoshima',
              'Kahriz', 'Kaifeng', 'Kalat',
              'Kaliningrad', 'Kalyan', 'Kampala', 'Kananga', 'Kanazawa', 'Kano',
              'Kanpur', 'Kansas City', 'Kaohsiung', 'Karachi',
              'Karaj', 'Kathmandu', 'Katsina', 'Kawaguchi', 'Kawasaki',
              'Kawasaki', 'Kayseri', 'Kazan', 'Kemerovo', 'Kerman',
              'Kermanshah', 'Khabarovsk', 'Kharkiv', 'Khartoum', 'Khemisset',
              'Khenifra', 'Khouribga', 'Khulna', 'Kyiv', 'Kigali',
              'Kingston', 'Kinshasa', 'Kirkuk', 'Kirov', 'Kisangani',
              'Kitakyushu', 'Klang', 'Kobe', 'Kocaeli', 'Kochi',
              'Kolhapur', 'Konia', 'Konya', 'Kosovo', 'Kota', 'Kota Kinabalu',
              'Kousseri', 'Krakow', 'Krasnodar', 'Krasnoyarsk',
              'Kryvyi Rih', 'Kuala Lumpur', 'Kuching', 'Kumamoto', 'Kumasi',
              'Kunming', 'Kurashiki', 'Gwangju', 'Kyoto', 'La Paz', 'La Plata',
              'Lagos', 'Lahore', 'Lucknow', 'Langfang', 'Lanzhou', 'Larache',
              'Las Pinas', 'Las Vegas', 'Leeds', 'Leipzig', 'Leon', 'Lehi',
              'Liaoyang', 'Libreville', 'Lilongwe', 'Lima', 'Lipetsk', 'Lisboa',
              'Liuzhou', 'Liverpool', 'Lopburi', 'Lodz', 'Lome', 'London',
              'Londrina', 'Long Beach', 'López Mateos City', 'Los Angeles',
              'Luancheng', 'Luanda', 'Lubumbashi', 'Ludhiana', 'Luoyang',
              'Lusaka', 'Lviv', 'Lyon', 'Ma\'anshan', 'Maceio', 'Madras',
              'Madrid', 'Madurai', 'Maha Sarakham', 'Maiduguri', 'Mysuru',
              'Makasar', 'Makhachkala', 'Malaga', 'Malang', 'Malatya',
              'Malatya', 'Malegaon', 'Manado', 'Managua', 'Manaus', 'Mandalay',
              'Manila', 'Mansilingan', 'Maoming', 'Maputo', 'Mar Del Plata',
              'Maracaibo', 'Marrakesh', 'Marseille', 'Mashhad', 'Matamoros',
              'Matola', 'Matsudo', 'Matsuyama', 'Mawlamyine', 'Mbuji-mayi',
              'Mecca', 'Medan', 'Medellin', 'Medina', 'Meerut', 'Meknes',
              'Melbourne', 'Memphis', 'Mendoza', 'Merida', 'Mersin', 'Mesa',
              'Mexicali', 'Mexico', 'Milan', 'Milwaukee', 'Minsk',
              'Mississauga', 'Mixco', 'Mogadishu', 'Mombasa', 'Monrovia',
              'Monterrey', 'Montevideo', 'Montreal', 'Moradabad', 'Morelia',
              'Moscow', 'Mosul', 'Mudanjiang', 'Multan', 'Munich', 'Mwanza',
              'Naberezhnye Chelny', 'Nakhon Pathom', 'Nagoya', 'Nagpur',
              'Nairobi', 'Namangan', 'Nanchang', 'Nanded', 'Nanjing',
              'Nanning', 'Nantong', 'Naples', 'Napoli', 'Narathiwat',
              'Nashville', 'Nashik', 'Natal', 'Naucalpan de Juarez', 'Neijiang', 'Nerima',
              'New Orleans', 'New York',
              'Newcastle', 'Nezahualcoyotl', 'Niamey', 'Niigata', 'Mykolaiv',
              'Ningbo', 'Nishinomiya', 'Niteroi', 'Nizhny Novgorod',
              'North Kansas City', 'Nouakchott', 'Novokuznetsk',
              'Novosibirsk', 'Nuremberg', 'Odessa', 'Ogun', 'Ooita', 'Okayama',
              'Okene', 'Oklahoma City', 'Omdurman', 'Omsk', 'Onicha', 'Onitsha',
              'Orenburg', 'Urmia', 'Osaka', 'Osasco', 'Osogbo', 'Oslo',
              'Ottawa', 'Ouagadougou', 'Ouagadougou', 'Ouarzazate', 'Oyo',
              'Padang', 'Pathum Thani', 'Palembang', 'Palermo',
              'Panshan', 'Panzhihua', 'Paris', 'Patna', 'Penza',
              'Pereira', 'Perm', 'Perth', 'Peshawar', 'Petaling Jaya',
              'Philadelphia', 'Phnom Penh', 'Phoenix', 'Pietermaritzburg',
              'Pimpri', 'Pingdingshan', 'Pointe-noire', 'Pontianak',
              'Port Elizabeth', 'Port Harcourt', 'Port-au-prince', 'Portland',
              'Porto Alegre', 'Poti', 'Poznan', 'Praha', 'Pretoria', 'Puebla',
              'Pune', 'Puyang', 'Pyongyang', 'Qingdao', 'Qinhuangdao',
              'Qiqihar', 'Qom', 'Quebec', 'Queretaro', 'Quetta', 'Quezon',
              'Quilmes', 'Quito', 'Rabat', 'Raipur', 'Rajkot', 'Rajpur',
              'Rajshahi', 'Ranchi', 'Rasht', 'Rawalpindi', 'Recife',
              'Reynosa', 'Ribeirao Preto', 'Riga', 'Rio De Janeiro', 'Riyadh',
              'Rome', 'Rongcheng', 'Rosario', 'Rostov-na-donu', 'Rotterdam',
              'Ryazan', 'Sacramento', 'Safi', 'Sagamihara',
              'Saharanpur', 'Saint Petersburg', 'Sakai', 'Sale', 'Salta',
              'Saltillo', 'Salvador', 'Samara', 'San Antonio', 'San Diego',
              'San Francisco', 'San Jose', 'San Juan', 'San Luis Potosi',
              'San Miguel De Tucuman', 'San Nicolas De Los Garza',
              'San Pedro Sula', 'San Salvador', 'Sana\'a',
              'Santa Cruz De La Sierra', 'Santa Fe', 'Santa Marta', 'Santiago',
              'Santiago', 'Santiago De Cuba', 'Santo Andre', 'Santo Domingo',
              'Sao Bernardo Do Campo', 'Sao Goncalo', 'Sao Joao De Meriti',
              'Sao Jose Dos Campos', 'Sao Luis', 'São Paulo', 'Sapporo',
              'Sar-e Pol', 'Saratov', 'Sargodha', 'Seattle',
              'Semarang', 'Sendai', 'Seoul', 'Settat', 'Sevilla', 'Shah Alam',
              'Shanghai', 'Shantou', 'Shaoguan', 'Sharjah', 'Shashi',
              'Sheffield', 'Shenyang', 'Shenzhen', 'Shihezi', 'Siliguri',
              'Shiraz', 'Shizuoka', 'Solapur', 'Sialkot', 'Singapore',
              'Skopje', 'Sofia', 'Sokoto', 'Songnam', 'Sorocaba',
              'South Boston', 'Soweto', 'Srinagar', 'Stockholm',
              'Stuttgart', 'Surabaya', 'Surakarta',
              'Surat', 'Suwon', 'Suzhou', 'Sydney', 'Tabriz', 'Daegu',
              'Taguig', 'Taian', 'Taichung', 'Tainan', 'Taipei', 'Taiyuan',
              'Taizhou', 'Tangier', 'Tangerang', 'Tanggu', 'Tangier',
              'Tangshan', 'Taounate', 'Taroudant', 'Tashkent', 'Taza',
              'Tbilisi', 'Tegucigalpa', 'Tehran', 'Tembisa', 'Teresina',
              'Thana', 'The Hague', 'Thiruvananthapuram', 'Tianjin', 'Tijuana',
              'Tipaza', 'Tiruchirappalli', 'Tirunelveli', 'Tlalnepantla',
              'San Pedro Tlaquepaque', 'Toluca', 'Tolyatti', 'Tomsk', 'Torino', 'Toronto',
              'Torreon', 'Tripoli', 'Trujillo', 'Tucson', 'Tucuman', 'Tula',
              'Tunes', 'Turin', 'Tuxtla Gutierrez', 'Tyumen', 'Uberlandia',
              'Ufa', 'Uijeongbu', 'Ujjain', 'Ulhasnagar', 'Ulyanovsk',
              'Urfa', 'Urumqi', 'Ussuriysk',
              'Utsunomiya', 'Vadodara', 'Valencia', 'Valencia', 'Vancouver',
              'Varanasi', 'Vaucluse', 'Veracruz', 'Vereeniging', 'Vijayawada',
              'Vilnius', 'Virginia Beach', 'Visakhapatnam', 'Vladivostok',
              'Volgograd', 'Voronezh', 'Oran', 'Warrap', 'Warangal',
              'Warri', 'Warsaw', 'Washington', 'Welkom', 'Wenzhou', 'Wien',
              'Winnipeg', 'Wroclaw', 'Wuhan', 'Wuhu', 'Wuxi', 'Xiamen', 'Xi\'an',
              'Xianyang', 'Xingtai', 'Xining', 'Xinxiang',
              'Xinyang', 'Xuchang', 'Xuzhou', 'Yancheng', 'Yangzhou', 'Yantai',
              'Yaounde', 'Yaroslavl', 'Yazd', 'Yekaterinburg', 'Yerevan',
              'Yichang', 'Yinchuan', 'Yingkou', 'Yogyakarta', 'Yokohama',
              'Yokosuka', 'Yongkang', 'Yueyang', 'Yunfu', 'Zagreb',
              'Zahedan', 'Zamboanga', 'Zamboanga City', 'Zapopan', 'Zaragoza',
              'Zaria', 'Zhangjiakou', 'Zhangzhou', 'Zhanjiang', 'Zhengzhou',
              'Zhenjiang', 'Zhuhai', 'Zhuzhou', 'Zibo', 'Zigong', 'Zunyi']

CAPITALS = [('AFGHANISTAN', 'KABUL'), ('ALBANIA', 'TIRANA'),
            ('ALGERIA', 'ALGIERS'), ('ANDORRA', 'ANDORRA LA VELLA'),
            ('ANGOLA', 'LUANDA'), ('Antigua and Barbuda', "St. JOHN'S"),
            ('ARGENTINA', 'BUENOS AIRES'), ('ARMENIA', 'YEREVAN'),
            ('AUSTRALIA', 'CANBERRA'), ('AUSTRIA', 'VIENNA'),
            ('AZERBAIJAN', 'BAKU'), ('The Bahamas', 'NASSAU'),
            ('BAHRAIN', 'MANAMA'), ('BANGLADESH', 'DHAKA'),
            ('BARBADOS', 'BRIDGETOWN'), ('BELARUS', 'MINSK'),
            ('BELGIUM', 'BRUSSELS'), ('BELIZE', 'BELMOPAN'),
            ('BENIN', 'PORTO-NOVO'), ('BHUTAN', 'THIMPHU'),
            ('BOLIVIA', 'SUCRE'), ('Bosnia and Herzegovina', 'SARAJEVO'),
            ('BOTSWANA', 'GABORONE'), ('BRAZIL', 'BRASILIA'),
            ('BRUNEI', 'BANDAR SERI BEGAWAN'), ('BULGARIA', 'SOFIA'),
            ('BURKINA FASO', 'OUAGADOUGOU'), ('BURUNDI', 'BUJUMBURA'),
            ('Cape Verde', 'PRAIA'), ('CAMBODIA', 'PHNOM PENH'),
            ('CAMEROON', 'YAOUNDE'), ('CANADA', 'OTTAWA'),
            ('CENTRAL AFRICAN REPUBLIC', 'BANGUI'), ('CHAD', "N'DJAMENA"),
            ('CHILE', 'SANTIAGO'), ('CHINA', 'BEIJING'),
            ('COLOMBIA', 'BOGOTÁ'), ('COMOROS', 'MORONI'),
            ('Democratic Republic of the Congo', 'KINSHASA'), ('CYPRUS', 'NICOSIA'),
            ('COSTA RICA', 'San José'), ("CÔTE D'IVOIRE", 'YAMOUSSOUKRO'),
            ('CROATIA', 'ZAGREB'), ('CUBA', 'HAVANA'),
            ('Czechia', 'PRAGUE'), ('DENMARK', 'COPENHAGEN'),
            ('DJIBOUTI', 'DJIBOUTI'), ('DOMINICA', 'ROSEAU'),
            ('DOMINICAN REPUBLIC', 'SANTO DOMINGO'), ('ECUADOR', 'QUITO'),
            ('EGYPT', 'CAIRO'), ('EL SALVADOR', 'SAN SALVADOR'),
            ('EQUATORIAL GUINEA', 'MALABO'), ('ERITREA', 'ASMARA'),
            ('ESTONIA', 'TALLINN'), ('ETHIOPIA', 'ADDIS ABABA'),
            ('FEDERATED STATES OF MICRONESIA', 'PALIKIR'), ('FIJI', 'SUVA'),
            ('FINLAND', 'HELSINKI'), ('FRANCE', 'PARIS'),
            ('GABON', 'LIBREVILLE'), ('Gambia', 'BANJUL'),
            ('GEORGIA', 'TBILISI'), ('GERMANY', 'BERLIN'),
            ('GREECE', 'ATHENS'), ('GRENADA', "St. GEORGE'S"),
            ('GUATEMALA', 'GUATEMALA CITY'), ('GUINEA', 'CONAKRY'),
            ('GUINEA-BISSAU', 'BISSAU'), ('GUYANA', 'GEORGETOWN'),
            ('HAITI', 'PORT-AU-PRINCE'), ('HONDURAS', 'TEGUCIGALPA'),
            ('HUNGARY', 'BUDAPEST'), ('ICELAND', 'Reykjavík'),
            ('INDIA', 'NEW DELHI'), ('INDONESIA', 'JAKARTA'),
            ('IRAN', 'TEHRAN'), ('IRAQ', 'BAGHDAD'),
            ('IRELAND', 'DUBLIN'), ('GHANA', 'ACCRA'),
            ('ISRAEL', 'JERUSALEM'), ('ISRAEL', 'TEL AVIV'),
            ('JAMAICA', 'KINGSTON'), ('JAPAN', 'TOKYO'),
            ('JORDAN', 'AMMAN'), ('ITALY', 'ROME'),
            ('KAZAKHSTAN', 'ASTANA'), ('KENYA', 'NAIROBI'),
            ('KIRIBATI', 'SOUTH TARAWA'), ('KOSOVO', 'PRISTINA'),
            ('KUWAIT', 'KUWAIT CITY'), ('KYRGYZSTAN', 'BISHKEK'),
            ('LAOS', 'VIENTIANE'), ('LATVIA', 'RIGA'),
            ('LESOTHO', 'MASERU'), ('LIBERIA', 'MONROVIA'),
            ('LIBYA', 'TRIPOLI'), ('LIECHTENSTEIN', 'VADUZ'),
            ('LITHUANIA', 'VILNIUS'), ('LUXEMBOURG', 'LUXEMBOURG'),
            ('Macedonia', 'SKOPJE'), ('LEBANON', 'BEIRUT'),
            ('MADAGASCAR', 'ANTANANARIVO'), ('MALAWI', 'LILONGWE'),
            ('MALAYSIA', 'KUALA LUMPUR'), ('MALDIVES', 'Malé'),
            ('MALI', 'BAMAKO'), ('MALTA', 'VALLETTA'),
            ('MARSHALL ISLANDS', 'MAJURO'), ('MAURITANIA', 'NOUAKCHOTT'),
            ('MAURITIUS', 'PORT LOUIS'), ('MEXICO', 'MEXICO CITY'),
            ('MOLDOVA', 'Chișinău'), ('MONACO', 'MONACO'),
            ('MONGOLIA', 'ULAANBAATAR'), ('MONTENEGRO', 'PODGORICA'),
            ('MOROCCO', 'RABAT'), ('MOZAMBIQUE', 'MAPUTO'),
            ('MYANMAR', 'Naypyidaw'), ('NAMIBIA', 'WINDHOEK'),
            ('NAURU', 'YAREN'), ('NEPAL', 'KATHMANDU'),
            ('THE NETHERLANDS', 'AMSTERDAM'), ('NEW ZEALAND', 'WELLINGTON'),
            ('NICARAGUA', 'MANAGUA'), ('NIGER', 'NIAMEY'),
            ('NORTH KOREA', 'PYONGYANG'), ('NORWAY', 'OSLO'),
            ('OMAN', 'MUSCAT'), ('PAKISTAN', 'ISLAMABAD'),
            ('PALAU', 'NGERULMUD'), ('Palestinian Territories', 'RAMALLAH'),
            ('PANAMA', 'PANAMA CITY'), ('PAPUA NEW GUINEA', 'PORT MORESBY'),
            ('PARAGUAY', 'ASUNCIÓN'), ('PERU', 'LIMA'),
            ('PHILIPPINES', 'MANILA'), ('POLAND', 'WARSAW'),
            ('PORTUGAL', 'LISBON'), ('QATAR', 'DOHA'),
            ('Congo-Brazzaville', 'BRAZZAVILLE'), ('ROMANIA', 'BUCHAREST'),
            ('RUSSIA', 'MOSCOW'), ('RWANDA', 'KIGALI'),
            ('Saint Kitts and Nevis', 'BASSETERRE'), ('NIGERIA', 'ABUJA'),
            ('SAINT VINCENT AND THE GRENADINES', 'KINGSTOWN'), ('SAINT LUCIA', 'CASTRIES'),
            ('SAMOA', 'APIA'), ('SAN MARINO', 'City of San Marino'),
            ('São Tomé and Príncipe', 'SÃO TOMÉ'), ('SAUDI ARABIA', 'RIYADH'),
            ('SENEGAL', 'DAKAR'), ('SERBIA', 'BELGRADE'),
            ('SEYCHELLES', 'VICTORIA'), ('SIERRA LEONE', 'FREETOWN'),
            ('SINGAPORE', 'SINGAPORE'), ('SLOVAKIA', 'BRATISLAVA'),
            ('SLOVENIA', 'LJUBLJANA'), ('SOLOMON ISLANDS', 'HONIARA'),
            ('SOMALIA', 'MOGADISHU'), ('SOUTH AFRICA', 'BLOEMFONTEIN'),
            ('SOUTH AFRICA', 'CAPE TOWN'), ('SOUTH AFRICA', 'PRETORIA'),
            ('SOUTH KOREA', 'SEOUL'), ('SOUTH SUDAN', 'JUBA'),
            ('SPAIN', 'MADRID'), ('SRI LANKA', 'COLOMBO'),
            ('SRI LANKA', 'SRI JAYAWARDENEPURA KOTTE'), ('SUDAN', 'KHARTOUM'),
            ('SURINAME', 'PARAMARIBO'), ('Eswatini', 'MBABANE'),
            ('SWEDEN', 'STOCKHOLM'), ('SWITZERLAND', 'BERN'),
            ('SYRIA', 'DAMASCUS'), ('TAJIKISTAN', 'DUSHANBE'),
            ('TANZANIA', 'DODOMA'), ('THAILAND', 'BANGKOK'),
            ('East Timor', 'DILI'), ('TOGO', 'LOMÉ'),
            ('TRINIDAD AND TOBAGO', 'PORT OF SPAIN'), ('TUNISIA', 'TUNIS'),
            ('TURKEY', 'ANKARA'), ('TURKMENISTAN', 'ASHGABAT'),
            ('TUVALU', 'Vaiaku'), ('UGANDA', 'KAMPALA'),
            ('UKRAINE', 'Kyiv'), ('TONGA', "Nuku'alofa"),
            ('UNITED ARAB EMIRATES', 'ABU DHABI'), ('UNITED KINGDOM', 'LONDON'),
            ('URUGUAY', 'MONTEVIDEO'), ('UZBEKISTAN', 'TASHKENT'),
            ('VANUATU', 'PORT VILA'), ('VATICAN CITY', 'VATICAN CITY'),
            ('VENEZUELA', 'CARACAS'), ('VIETNAM', 'HANOI'),
            ('YEMEN', "SANA'A"), ('United States of America', 'WASHINGTON, D.C.'),
            ('ZAMBIA', 'LUSAKA'), ('ZIMBABWE', 'HARARE')]


def read_csv_into_dict(f):
    r = csv.reader(f, delimiter=';')
    header = next(r)
    result = {}
    for row in r:
        item = {}
        for i in range(1, len(row)):
            item[header[i]] = row[i]
        result[row[0]] = item
    return result

if len(sys.argv) < 2:
    print('Usage: {} <path_to_places_json_or_csv>'.format(sys.argv[0]))
    sys.exit(1)

with open(sys.argv[1], 'r') as f:
    if '.csv' in sys.argv[1]:
        places = read_csv_into_dict(f)
    else:
        places = json.load(f)

countries_name = re.sub(r'places(?=[._-])', 'countries', sys.argv[1])
with open(countries_name, 'r') as f:
    if '.csv' in countries_name:
        countries = read_csv_into_dict(f)
    else:
        countries = json.load(f)

place_names = defaultdict(list)
for pid, names in places.items():
    for k in ('name_en', 'int_name', 'name'):
        if k in names:
            place_names[names[k].lower()].append(pid)

for city in CITY_NAMES:
    if city.lower() not in place_names:
        print('City not found: {}'.format(city))

for country, city in CAPITALS:
    pids = place_names.get(city.lower())
    if not pids:
        print('Capital not found: {}, {}'.format(city.title(), country.title()))
    else:
        pcountries = set()
        for pid in pids:
            for k, name in countries.get(str(places[pid]['country']), {}).items():
                if k in ('name_en', 'int_name', 'name'):
                    pcountries.add(name.lower())
        if country.lower() not in pcountries:
            print('Country {} for capital {} not found, instead: {}'.format(
                country.title(), city.title(), ', '.join([c.title() for c in sorted(pcountries)])))
